# [START runtime]
runtime: nodejs
env: flex
service: lv-mx-report
# [END runtime]

# [START handlers]
# handlers:
#  - url: /
#    static_files: build/index.html
#    upload: build/index.html

#  - url: /(.*)
#    static_files: build/\1
#    upload: build/(.*)
# [END handlers]

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10